### ISSUE TITLE
minDecimal / maxDecimal?

### ISSUE THREAD

**Issue by SuddenGunter** [feliixx/mgodatagen#20]
int, long, double are documented in readme to have min and max limits, but not decimal.
why so?
is there are a way to limit decimals?

**Comment by feliixx** [comment]
Hi @SuddenGunter, there is currently no way to limit decimals. The decimal128 generator just create random 128 bit number ( relevant code is here: [generators.go#L186](https://github.com/feliixx/mgodatagen/blob/master/datagen/generators/generators.go#L186) )

I did it that way because I had no idea on how to generate random bounded 128 bit decimal when I created the library. 

If this is something you actually need, feel free to submit an implementation !

**Comment by SuddenGunter** [comment]
Yes, I do need (well, not need but want :D) it.

I'm trying to create 1-click-to-run playground for my MongoDB aggregation pipeline testing. And I want to generate banking transactions using your tool.
The approach I'd used yesterday was to generate the amount using `long` generator and then divide everything in DB by 100.
It works, but kinda slow for 5M transactions (and I want to make some testing on 50M) plus involves manual step when I need to connect to DB and run update.

Another problem with decimal generator I see is that it may have lot's of numbers after period, and even if I would be able to limit it `from -1000 to 1000` - it won't be ok for my case, because of all that `0.111111.....`.
Maybe it would be better to introduce some `monetary` generator where we can specify max/min limits and  `numbers after period count`?
Or just add these limitations as optional for decimal?

What do you think?
